#pragma once

typedef enum {
    PUBSUB_EVENT_UID_SENT_SUCCESSFULLY,
    PUBSUB_EVENT_UID_SENT_FAILED,
    PUBSUB_EVENT_SERVER_RESPONDED_SUCCESSFULLY,
    PUBSUB_EVENT_SERVER_TIMEOUT,
    PUBSUB_EVENT_SERVER_COMMAND_RECEIVED,
    PUBSUB_EVENT_NONE,

    PUBSUB_EVENT_SERVER_CMD_AVAILABLE,
    PUBSUB_EVENT_SERVER_REGISTER_CMD
}pub_sub_events_t;

pub_sub_events_t pub_sub_event_handler();
