#pragma once

#define WIFI_CONNECTED_BEEP_DELAY_ms    500
#define WIFI_DISCONNECTED_BEEP_DELAY_ms 50

#define MQTT_CONNECTED_BEEP_DELAY_ms    500
#define MQTT_DISCONNECTED_BEEP_DELAY_ms 50

#define RFID_SCAN_SUCCESSFUL_BEEP_INTERVAL_ms   50
#define RFID_SCAN_UNSUCCESSFUL_BEEP_INTERVAL_ms 100

#define SERVER_SUCCESSFUL_PUBLISH_BEEP_DELAY_ms  100
#define SERVER_UNSUCCESSFUL_PUBLISH_BEEP_DELAY_ms 80

#define SERVER_SUCCESSFUL_RESPONSE_BEEP_DELAY_ms   100
#define SERVER_UNSUCCESSFUL_RESPONSE_BEEP_DELAY_ms 50


#define BUZZER_PIN 27
#define TICK_MS 50